name: santander_consumer_clientes
description: App movil de clientes - Santander Consumer Peru.
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.68.0
  http: ^1.2.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.0
  intl: ^0.20.2
  google_fonts: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/santander_icon.png
  adaptive_icon_background: "#EC0000"
  adaptive_icon_foreground: assets/branding/santander_icon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/branding/santander_icon.png
    - assets/branding/santander_logo.png
